# Generated by Django 3.2.9 on 2021-11-07 20:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_lat', models.FloatField(null=True)),
                ('start_long', models.FloatField(null=True)),
                ('end_lat', models.FloatField(null=True)),
                ('end_long', models.FloatField(null=True)),
                ('race_day_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('racer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bike_manufacturer', models.CharField(max_length=50, null=True)),
                ('bike_model', models.CharField(max_length=50, null=True)),
                ('email_address', models.CharField(max_length=50, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_admin', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(null=True)),
                ('last_checked_in_time', models.DateTimeField(blank=True, null=True)),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceday.race')),
                ('racer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceday.racer')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceday.racer'),
        ),
    ]
