# Generated by Django 3.2.9 on 2021-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceday', '0004_rename_event_id_result_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='location_offset',
            field=models.FloatField(null=True),
        ),
    ]
